name: PabloLogowanie
version: 1.0
author: PabloTL
main: PabloTL.Logowanie.Main
commands:
    login:
        description: Komenda plugin PabloLogowanie
        usage: /<command>
    register:
        description: Komenda plugin PabloLogowanie
        usage: /<command>
